export const DEFAULT_URL = "http://localhost:9000/api"
export const ADAPTATION_GOALS = "adaptationbgoal"
export const ADAPTATION_PROGRAM = "adaptationprogram"
export const ADAPTATION_CONTACTS = "adaptationcontact"
export const ADAPTATION_DOCUMENT = "adaptationdocument"
