// export const DEFAULT_URL = "http://localhost:9000/api"
export const DEFAULT_URL = "http://51.250.15.127:9000/api-active"
export const ADAPTATION_GOALS = "adaptationbgoal"
export const ADAPTATION_PROGRAM = "adaptationprogram"
export const ADAPTATION_CONTACTS = "adaptationcontact"
export const ADAPTATION_DOCUMENT = "adaptationdocument"
export const ADAPTATION_LEVELS = "adaptationlevel"
export const ADAPTATION_STAGE = "adaptationstage"
export const ADAPTATION_CUSTOMER = "customer"
export const ADAPTATION_EMPLOYEE = "employee"

export const CONTACTS =  "icontacts"
export const DIRECTORY = "directory"
export const CANDIDATE_LIST = "candidate/"
export const CANDIDATE_FILTER = "candidate/filter/"
