export const PATH_EMPLOYEES_LIST = "/employees"
export const PATH_APPEAL = "/appeal"
export const PATH_PROGRAM_LIST = "/programs"
export const PATH_REFERENCE = "/reference"
export const PATH_SETTINGS = "/settings"
